
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 72
#define YY_END_OF_BUFFER 73
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_acclist[249] =
    {   0,
       73,   72,    1,   72,    2,   72,   72,   72,16391,16392,
       72,16391,16392,    6,   72,    1,    6,   72,    2,    6,
       72,    5,    6,   72,    6,   72,    1,   72,   10,   72,
       72,   12,   72,   13,   72,   72,    1,   72,   15,   72,
       72,   17,   72,   18,   72,   72,    1,   72,   72,   26,
       72,   72,   26,   72,   26,   72,   26,   72,   26,   72,
       26,   72,   36,   72,   37,   72,   72,   39,   72,   40,
       72,   72,   42,   72,   43,   72,   72,   45,   72,   46,
       72,   72,   48,   72,   72,   49,   50,   72,   50,   72,
       53,   72,   54,   72,    1,   72,   72,   34,   72,   72,

       33,   72,   34,   72,   34,   72,   34,   72,   34,   72,
       55,   72,   56,   72,   72,   58,   72,   59,   72,   72,
       61,   72,   62,   72,   63,   72,   72,   65,   72,   64,
       72,   67,   72,   69,   72,   71,   72,   68,   72,   70,
       72,    2,    3,16391,16392,16391,16392,    5,    4,   10,
       14,   15,   18,   19,   26,   26,   26,   26,   26,   26,
       37,   38,   40,   41,   43,   44,   45,   52,   51,   50,
       53,   33,   56,   57,   59,   60,   61,   66,   64,   68,
    16391,16392,   27,   26,   26,   26,   26,   26,   47,   35,
    16391,16392,   11,   16,   26,   26,   26,   26,   26,16391,

    16392,   26,   26,   26,   26,   26,16391,16392,   26,   26,
       26,   26,   26,16391,16392,   26,   26,   26,   26,    9,
    16391,16392,   26,   26,   26,   25,   26,   32,   26,   26,
       22,   26,   26,   21,   26,   26,   28,   30, 8200,   26,
       26,   26,   31,   23,   24,   29,   20, 8199
    } ;

static const flex_int16_t yy_accept[360] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        3,    5,    7,    8,   11,   14,   16,   19,   22,   25,
       27,   29,   31,   32,   34,   36,   37,   39,   41,   42,
       44,   46,   47,   49,   50,   52,   53,   55,   57,   59,
       61,   63,   65,   67,   68,   70,   72,   73,   75,   77,
       78,   80,   82,   83,   85,   86,   89,   91,   93,   95,
       97,   98,  100,  101,  103,  105,  107,  109,  111,  113,

      115,  116,  118,  120,  121,  123,  125,  127,  128,  130,
      132,  134,  136,  138,  140,  142,  143,  144,  144,  146,
      146,  148,  149,  150,  150,  150,  151,  151,  151,  152,
      152,  152,  153,  153,  154,  154,  155,  155,  155,  155,
      155,  156,  156,  157,  158,  159,  160,  161,  162,  162,
      163,  164,  164,  165,  166,  166,  167,  168,  168,  169,
      170,  171,  172,  172,  172,  172,  172,  172,  173,  173,
      173,  173,  173,  174,  174,  175,  176,  176,  177,  178,
      179,  180,  181,  181,  183,  183,  183,  184,  184,  185,
      186,  187,  188,  189,  189,  190,  191,  191,  191,  191,

      191,  191,  191,  193,  193,  194,  194,  195,  195,  195,
      196,  197,  198,  199,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  202,  202,  203,  204,  205,  206,
      207,  207,  207,  207,  207,  207,  207,  207,  209,  209,
      210,  211,  212,  213,  214,  214,  214,  214,  214,  214,
      214,  214,  216,  216,  217,  218,  219,  219,  219,  220,
      220,  220,  220,  220,  220,  220,  220,  223,  223,  224,
      225,  226,  226,  228,  228,  228,  228,  228,  229,  229,
      229,  229,  229,  229,  230,  231,  231,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  233,  234,  234,

      234,  234,  234,  234,  234,  234,  234,  235,  236,  237,
      237,  238,  238,  239,  239,  239,  239,  239,  240,  240,
      241,  242,  242,  242,  242,  242,  242,  242,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  244,
      244,  244,  244,  245,  246,  246,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  248,  248,  249,  249
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    4,    5,    1,    6,
        7,    8,    1,    9,   10,    1,   11,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   13,   14,    1,
       15,   16,    1,    1,   17,   18,   18,   18,   18,   19,
       20,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
        1,    1,    1,    1,   21,    1,   22,   23,   12,   12,

       24,   25,   12,   26,   27,   12,   12,   28,   29,   30,
       31,   32,   12,   33,   34,   35,   36,   37,   12,   12,
       38,   12,   39,   40,   41,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[42] =
    {   0,
        1,    2,    3,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    2,    1,    1,    1,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    1,    1,
        1
    } ;

static const flex_int16_t yy_base[378] =
    {   0,
        0,    0,   40,   50,   61,    0,  102,    0,  143,    0,
      184,    0,  225,    0,  266,    0,  307,    0,  348,    0,
      389,    0,  430,    0,  471,    0,  512,    0,  553,    0,
      594,    0,  635,    0,  676,    0,  717,    0, 1106, 1107,
     1107,    0, 1097,   43,  757, 1107, 1107,    0,   38, 1096,
      758,    0, 1090, 1107, 1107,   45,  759,    0, 1089, 1107,
        0,  760,  762,  763,    0, 1088, 1072, 1072, 1068, 1062,
     1074, 1107,    0,  764, 1107,    0,  766, 1107,    0,  767,
        0, 1107,  771, 1107, 1079,    0,    0,    0, 1107,  774,
      780, 1107, 1081,    0, 1065, 1061, 1056, 1068, 1107,    0,

      781, 1107,    0,  782,    0, 1107, 1107, 1073, 1107,    0,
     1107, 1107, 1107,    0, 1107,    0, 1107,  784,  786, 1075,
      787,   49, 1107,  788, 1074,    0, 1071,  789, 1107,  791,
     1072,    0, 1069,    0,  796, 1107,  800, 1070,  803, 1068,
        0, 1066, 1048, 1049, 1051, 1055, 1043,    0,  804, 1107,
        0,  805, 1107,    0,  807, 1107,    0,  809, 1107,  761,
        0,    0,  812, 1062,  810, 1060, 1058,    0, 1040, 1041,
     1048, 1036,    0,  813, 1107,    0,  814, 1107,    0, 1107,
        0,    0, 1053,  820,  790,  806, 1107,  824, 1041, 1044,
     1030, 1029, 1036,  828, 1107, 1107,  829, 1036, 1026, 1027,

     1032,  833,  835,  830, 1107,  834, 1107,  836, 1031, 1035,
     1028, 1028, 1030, 1031,  838, 1019, 1029, 1026, 1014, 1026,
      840, 1020, 1013,  848, 1015, 1021, 1022, 1020, 1007, 1017,
     1017, 1015, 1004, 1015, 1012, 1004, 1011,  849, 1005, 1007,
      996, 1001,  852, 1000,  998, 1002,  996,  990,  995,  995,
      992,  854,  985,  984,  983,  996,  861, 1003,  991,  985,
      978,  985,  973,  986,  974,  979,  862,  983,  866,  984,
      971,  837,    0,  982,  868,  973,  973, 1107,  977,  978,
      982,  870,  985,  962,  961,  864, 1107,  962,  878,  981,
      971,  969,  974,  957,  953,  880,  964,  965,  882,  884,

      958,  954,  948,  887,  948,  885, 1107,  948,  946,  892,
     1107,  890, 1107,  946,  951,  943,  894, 1107,  946,  897,
      952,  899,  900,  944,  945,  902,  960,  903,  904,  959,
      905,  958,  941,  946,  906,  907,  952,  909, 1107,  935,
      921,  912, 1107, 1107,  919, 1107,  920,  923,  922,  922,
      920,  924,  929,  931, 1107,  936, 1107, 1107,  958,  962,
      965,  945,  943,  942,  940,  939,  937,  936,  932,  924,
      921,  918,  842,  840,  837,   51,   46
    } ;

static const flex_int16_t yy_def[378] =
    {   0,
      358,    1,  359,  359,  358,    5,  358,    7,  358,    9,
      358,   11,  358,   13,  358,   15,  358,   17,  358,   19,
      358,   21,  358,   23,  358,   25,  358,   27,  358,   29,
      358,   31,  358,   33,  358,   35,  358,   37,  358,  358,
      358,  360,  358,  361,  361,  358,  358,  360,  358,  358,
      358,  362,  358,  358,  358,  358,  358,  363,  358,  358,
      364,  358,  358,  358,  365,  358,  365,  365,  365,  365,
      365,  358,  366,  358,  358,  367,  358,  358,  368,  358,
      369,  358,  358,  358,  358,  370,  370,  371,  358,  358,
      358,  358,  358,  372,  358,  358,  358,  358,  358,  373,

      358,  358,  374,  358,  375,  358,  358,  358,  358,  376,
      358,  358,  358,  377,  358,  360,  358,  358,  361,  358,
      361,  358,  358,  358,  358,  362,  358,  358,  358,  358,
      358,  363,  358,  364,  358,  358,  358,  358,  358,  358,
      365,  358,  365,  365,  365,  365,  365,  366,  358,  358,
      367,  358,  358,  368,  358,  358,  369,  358,  358,  358,
      370,  371,  358,  358,  358,  358,  358,  372,  358,  358,
      358,  358,  373,  358,  358,  374,  358,  358,  375,  358,
      376,  377,  358,  361,  358,  358,  358,  358,  365,  365,
      365,  365,  365,  358,  358,  358,  358,  358,  358,  358,

      358,  358,  361,  358,  358,  358,  358,  358,  358,  365,
      365,  365,  365,  365,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  361,  358,  365,  365,  365,  365,  365,
      358,  358,  358,  358,  358,  358,  358,  361,  358,  365,
      365,  365,  365,  365,  358,  358,  358,  358,  358,  358,
      358,  361,  358,  365,  365,  365,  358,  358,  365,  358,
      358,  358,  358,  358,  358,  358,  361,  358,  365,  365,
      365,  358,  365,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  365,  365,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  365,  365,  358,  358,

      358,  358,  358,  358,  358,  358,  358,  365,  365,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  365,
      365,  358,  358,  358,  358,  358,  358,  365,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,    0,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358
    } ;

static const flex_int16_t yy_nxt[1149] =
    {   0,
       40,   41,   41,   42,   40,   40,   40,   40,   40,   40,
       43,   44,   40,   40,   40,   40,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   45,   44,   40,   40,
       40,   47,   41,   48,  118,  122,  128,   49,  123,  182,
       50,   47,   41,   48,  181,  120,  122,   49,  129,  123,
       50,   40,   51,   41,   42,   40,   40,   40,   40,   40,
       40,   43,   52,   53,   40,   40,   40,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   40,

       40,   40,   40,   41,   41,   42,   40,   40,   40,   40,
       54,   40,   43,   55,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       40,   40,   56,   40,   57,   41,   42,   40,   40,   40,
       40,   40,   40,   43,   58,   59,   40,   40,   40,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   40,   40,   40,   40,   41,   41,   42,   40,   40,
       40,   40,   60,   40,   43,   61,   40,   40,   40,   40,

       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   40,   40,   62,   40,   63,   41,   42,   40,
       40,   64,   40,   40,   40,   43,   65,   66,   40,   40,
       40,   65,   65,   65,   65,   65,   67,   65,   65,   68,
       65,   69,   65,   65,   65,   65,   65,   65,   70,   65,
       65,   71,   65,   40,   40,   40,   40,   41,   41,   42,
       40,   40,   40,   40,   72,   40,   43,   73,   40,   40,
       40,   40,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,

       73,   73,   73,   73,   40,   40,   74,   40,   41,   41,
       42,   40,   40,   40,   40,   75,   40,   43,   76,   40,
       40,   40,   40,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   40,   40,   77,   40,   41,
       41,   42,   40,   40,   40,   40,   78,   40,   43,   79,
       40,   40,   40,   40,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   40,   40,   80,   40,
       41,   41,   42,   40,   40,   40,   40,   40,   40,   43,

       81,   40,   82,   40,   40,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   40,   40,   40,
       40,   41,   41,   42,   40,   40,   83,   40,   84,   85,
       43,   86,   40,   40,   40,   40,   87,   87,   87,   87,
       87,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   40,   40,
       40,   40,   41,   41,   42,   40,   40,   40,   40,   40,
       40,   43,   88,   40,   89,   40,   40,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,

       88,   88,   88,   88,   88,   88,   88,   88,   88,   40,
       40,   40,   40,   90,   41,   42,   40,   40,   91,   40,
       40,   40,   43,   92,   93,   40,   40,   40,   94,   94,
       94,   94,   40,   95,   92,   92,   92,   92,   92,   92,
       92,   96,   92,   92,   92,   97,   92,   92,   98,   92,
       40,   40,   40,   40,   41,   41,   42,   40,   40,   40,
       40,   99,   40,   43,  100,   40,   40,   40,   40,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,   40,   40,  101,   40,   41,   41,   42,   40,   40,

       40,   40,  102,   40,   43,  103,   40,   40,   40,   40,
      103,  103,  103,  103,  103,  103,  103,  103,  103,  103,
      103,  103,  103,  103,  103,  103,  103,  103,  103,  103,
      103,  103,   40,   40,  104,   40,   41,   41,   42,   40,
       40,   40,   40,   40,   40,   43,  105,   40,  106,   40,
       40,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,   40,   40,   40,   40,   41,   41,   42,
      107,   40,   40,   40,   40,  108,   43,  109,   40,   40,
       40,   40,  110,  110,  110,  110,   40,  109,  109,  109,

      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,   40,   40,   40,   40,   41,   41,
       42,  111,   40,   40,   40,   40,   40,   43,  112,   40,
      113,   40,   40,  114,  114,  114,  114,   40,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,   40,  115,   40,  118,  124,
      130,  135,  194,  137,  139,  149,  195,  152,  155,  120,
      125,  131,  158,  136,  138,  163,  140,  150,  121,  153,
      156,  165,  174,  177,  159,  118,  164,  118,  118,  124,
      128,  204,  130,  166,  175,  178,  120,  135,  120,  120,

      125,  137,  129,  131,  139,  149,  152,  206,  155,  136,
      158,  165,  138,  163,  174,  177,  140,  150,  153,  184,
      156,  118,  159,  166,  164,  208,  175,  178,  205,  194,
      215,  204,  120,  195,  221,  206,  118,  208,  286,  215,
      179,  221,  209,  176,  207,  173,  203,  120,  216,  118,
      118,  222,  223,  257,  209,  118,  224,  216,  222,  223,
      120,  120,  257,  118,  258,  286,  120,  282,  205,  289,
      238,  282,  207,  258,  120,  287,  252,  267,  283,  289,
      290,  306,  283,  310,  310,  312,  306,  311,  317,  317,
      290,  312,  318,  310,  310,  317,  317,  311,  326,  318,

      329,  331,  287,  326,  336,  329,  331,  342,  336,  327,
      345,  330,  332,  342,  327,  337,  330,  332,  307,  337,
      345,  168,  313,  307,  162,  354,  354,  161,  313,  355,
      356,  356,  354,  354,  357,  157,  355,  356,  356,  154,
      151,  357,  148,  141,  343,  134,  132,  346,  126,  353,
      343,  352,  351,  350,  349,  348,  347,  346,   46,   46,
       46,   46,  116,  116,  344,  116,  119,  341,  119,  340,
      339,  338,  335,  334,  333,  328,  325,  324,  323,  322,
      321,  320,  319,  316,  315,  314,  309,  308,  305,  304,
      303,  302,  301,  300,  299,  298,  297,  296,  295,  294,

      293,  292,  291,  288,  285,  284,  281,  280,  279,  278,
      277,  276,  275,  274,  273,  272,  271,  270,  269,  268,
      266,  265,  264,  263,  262,  261,  260,  259,  256,  255,
      254,  253,  251,  250,  249,  248,  247,  246,  245,  244,
      243,  242,  241,  240,  239,  237,  236,  235,  234,  233,
      232,  231,  230,  229,  228,  227,  226,  225,  220,  219,
      218,  217,  214,  213,  212,  211,  210,  202,  201,  200,
      199,  198,  197,  196,  167,  193,  192,  191,  190,  189,
      188,  187,  142,  186,  133,  185,  127,  183,  180,  172,
      171,  170,  169,  167,  160,  147,  146,  145,  144,  143,

      142,  133,  127,  117,  117,  358,   39,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358
    } ;

static const flex_int16_t yy_chk[1149] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    3,    3,   44,   49,   56,    3,   49,  377,
        3,    4,    4,    4,  376,   44,  122,    4,   56,  122,
        4,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,

        5,    5,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,

       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,

       15,   15,   15,   15,   15,   15,   15,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,

       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,

       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   31,   31,   31,   31,   31,   31,

       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,

       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   45,   51,
       57,   62,  160,   63,   64,   74,  160,   77,   80,   45,
       51,   57,   83,   62,   63,   90,   64,   74,   45,   77,
       80,   91,  101,  104,   83,  118,   90,  119,  121,  124,
      128,  185,  130,   91,  101,  104,  118,  135,  119,  121,

      124,  137,  128,  130,  139,  149,  152,  186,  155,  135,
      158,  165,  137,  163,  174,  177,  139,  149,  152,  121,
      155,  184,  158,  165,  163,  188,  174,  177,  185,  194,
      197,  204,  184,  194,  202,  206,  203,  208,  272,  215,
      375,  221,  188,  374,  186,  373,  184,  203,  197,  224,
      238,  202,  202,  243,  208,  252,  203,  215,  221,  221,
      224,  238,  257,  267,  243,  286,  252,  269,  204,  275,
      224,  282,  206,  257,  267,  272,  238,  252,  269,  289,
      275,  296,  282,  299,  299,  300,  306,  299,  304,  304,
      289,  312,  304,  310,  310,  317,  317,  310,  320,  317,

      322,  323,  286,  326,  328,  329,  331,  335,  336,  320,
      338,  322,  323,  342,  326,  328,  329,  331,  296,  336,
      345,  372,  300,  306,  371,  352,  352,  370,  312,  352,
      353,  353,  354,  354,  353,  369,  354,  356,  356,  368,
      367,  356,  366,  365,  335,  364,  363,  338,  362,  351,
      342,  350,  349,  348,  347,  341,  340,  345,  359,  359,
      359,  359,  360,  360,  337,  360,  361,  334,  361,  333,
      332,  330,  327,  325,  324,  321,  319,  316,  315,  314,
      309,  308,  305,  303,  302,  301,  298,  297,  295,  294,
      293,  292,  291,  290,  288,  285,  284,  283,  281,  280,

      279,  277,  276,  274,  271,  270,  268,  266,  265,  264,
      263,  262,  261,  260,  259,  258,  256,  255,  254,  253,
      251,  250,  249,  248,  247,  246,  245,  244,  242,  241,
      240,  239,  237,  236,  235,  234,  233,  232,  231,  230,
      229,  228,  227,  226,  225,  223,  222,  220,  219,  218,
      217,  216,  214,  213,  212,  211,  210,  209,  201,  200,
      199,  198,  193,  192,  191,  190,  189,  183,  172,  171,
      170,  169,  167,  166,  164,  147,  146,  145,  144,  143,
      142,  140,  138,  133,  131,  127,  125,  120,  108,   98,
       97,   96,   95,   93,   85,   71,   70,   69,   68,   67,

       66,   59,   53,   50,   43,   39,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358
    } ;

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
(yy_lp) = (yy_full_lp); /* restore orig. accepting pos. */ \
(yy_state_ptr) = (yy_full_state); /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "main.l"
/* Bobelniceanu Darius-Andrei - 331CC */
#line 4 "main.l"
#include <iostream>
#include <string>
#include <vector>
#include <stack>
#include <unordered_map>

extern "C"
{
    extern int yylex(void);
}

using namespace std;

// Tine cont de numarul de comentarii multi-line deschide, pentru cazuri ca "/* /* */ */"
int comments_nested = 0;

typedef struct {
    string name; // numele variabilei
    vector<char> domain; // valorile pe care le poate lua variabila 
} Variable;
vector<Variable> variables;
// Stochez temporar variabilele citite aici pana le termin de citit integral
Variable temp_variable;

void reset_temp_variable() {
    temp_variable.name = "";
    temp_variable.domain.clear();
}

int find_variable(string name) {
    for (int i = 0; i < variables.size(); i++) {
        if (variables[i].name == name) {
            return i;
        }
    }
    return -1;
}

// Structuri pentru date care nu pot fi scrise direct/sunt necesare mai tarziu
typedef struct {
    bool deterministic; // automat determinist (true/false)
    vector<char> alphabet; // literele alfabetului 
    vector<string> states; // multimea starilor automatului
    vector<string> final_states; // multimea starilor finale 
    // Stocheaza numarul tranzitiilor pentru fiecare grupare stare + caracter
    // Exemplu: q0 -> (a -> q1; a -> q2;) => transitions["q0"]['a'] = 2
    // Sau q0 -> (a -> q1; b -> q2;) => transitions["q0"]['a'] = 1 si transitions["q0"]['b'] = 1
    unordered_map<string, unordered_map<char, int>> transitions; // map pentru evidenta tranzitiilor
    // Stocheaza literele/domeniul variabilelor din tranzitie pana ajung la starea finala
    // Exemplu: a, b -> q2 => last_letters = {a, b} sau x -> q2 => last_letters = {a, b}
    vector<char> last_letters;
    // Starea initiala a tranzitiilor dintr-un bloc
    string current_initial;
    // Cate variabile din vector sunt locale
    int my_variables;
} AutomatonData;
AutomatonData automaton;

// resetarea variabilelor automatului pentru procesarea altuia
void reset_automaton_data() {
    automaton.deterministic = true; // presupunem ca automatul este determinist
    automaton.alphabet.clear();
    automaton.states.clear();
    automaton.final_states.clear();
    automaton.transitions.clear();
    automaton.last_letters.clear();
    automaton.my_variables = 0;
}

typedef enum {
    GN = 1, // Nerestrictionata
    GDC = 2, // Dependenta de context
    GIC = 3, // Independenta de context
    GR = 4 // Regulata
} Grammars;

typedef struct {
    Grammars type; // tipul gramaticii conform enum-ului (GN, GDC, GIC, GR)
    vector<char> alphabet; // alfabetul gramaticii
    int nonterminal_count; // numarul de neterminali
    int terminal_count; // numarul de terminali
    int start_size; // dimensiunea partii stangi a sagetii de la productie
    int production_rules; // numarul total de reguli de productie
    // Ultimul simbol citit, pentru cazurile in care o productie se termina cu "e"
    string last_read;
    int my_variables; // cate variabile locale are gramatica
} GrammarData;
GrammarData grammar;

// resetarea variabilelor gramaticii pentru procesarea alteia
void reset_grammar_data() {
    grammar.type = GR; // plecam de la presupunerea ca este regulata 
    // si pe masura ce observam incalcarea regulilor, schimbam tipul
    grammar.alphabet.clear();
    grammar.nonterminal_count = 0;
    grammar.terminal_count = 0;
    grammar.start_size = 0;
    grammar.production_rules = 0;
    grammar.last_read = "";
    grammar.my_variables = 0;
}

// resetarea variabilelor productiilor din gramatica pentru procesarea uneia noi
void reset_grammar_production_data() {
    grammar.nonterminal_count = 0;
    grammar.terminal_count = 0;
    grammar.start_size = 0;
}

#line 967 "lex.yy.c"

#line 969 "lex.yy.c"

#define INITIAL 0
#define IN_COMMENT 1
#define VARIABLE 2
#define IN_VARIABLE 3
#define L_VARIABLE 4
#define L_IN_VARIABLE 5
#define AUTOMATON_MAIN 6
#define A_ALPHABET 7
#define A_STATES 8
#define A_FINAL_STATES 9
#define A_INITIAL_STATE 10
#define A_TRANSITIONS 11
#define A_TRANSITIONS_END 12
#define GRAMMAR_MAIN 13
#define G_NONTERMINALS 14
#define G_ALPHABET 15
#define G_START_SYMBOL 16
#define G_PRODUCTIONS 17
#define G_PRODUCTIONS_END 18

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

        static int yy_start_stack_ptr = 0;
        static int yy_start_stack_depth = 0;
        static int *yy_start_stack = NULL;
    
    static void yy_push_state ( int _new_state );
    
    static void yy_pop_state ( void );
    
    static int yy_top_state ( void );
    
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 144 "main.l"


#line 1223 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 359 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1107 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     (yy_looking_for_trail_begin) )
					{
					if ( yy_act == (yy_looking_for_trail_begin) )
						{
						(yy_looking_for_trail_begin) = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					(yy_looking_for_trail_begin) = yy_act & ~YY_TRAILING_MASK;
					(yy_looking_for_trail_begin) |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					(yy_full_match) = yy_cp;
					(yy_full_state) = (yy_state_ptr);
					(yy_full_lp) = (yy_lp);
					break;
					}
				++(yy_lp);
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 146 "main.l"
{
    // "\n", " " si "\t" sunt ignorate implicit peste tot
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 150 "main.l"
{ /* "." face match si ignora orice pana la newline */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 151 "main.l"
{
    if (comments_nested == 0) {
        comments_nested++;
        BEGIN(IN_COMMENT);
    } else {
        comments_nested++;
    }
}
	YY_BREAK

case 4:
YY_RULE_SETUP
#line 160 "main.l"
{
        if (comments_nested == 1) {
            comments_nested--;
            BEGIN(INITIAL);
        } else {
            comments_nested--;
        }
    }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 168 "main.l"
;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 169 "main.l"
{ /* Ignora alte caractere; newline e eliminat de prima regula cu "<*>" */ }
	YY_BREAK


case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 173 "main.l"
{
        // Cu look-ahead ca sa citesc strict numele automatului
        reset_automaton_data();
        cout << "Automat cu numele: \"" << yytext << "\"" << endl;
        yy_push_state(AUTOMATON_MAIN);
    }
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 179 "main.l"
{
        reset_grammar_data();
        cout << "Gramatica cu numele: \"" << yytext << "\"" << endl;
        yy_push_state(GRAMMAR_MAIN);
    }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 184 "main.l"
{
        reset_temp_variable();
        yy_push_state(VARIABLE);
    }
	YY_BREAK


case 10:
YY_RULE_SETUP
#line 191 "main.l"
{
        temp_variable.name = yytext;
    }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 194 "main.l"
{
        yy_push_state(IN_VARIABLE);
    }
	YY_BREAK


case 12:
YY_RULE_SETUP
#line 200 "main.l"
; // ignor virgulele
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 201 "main.l"
{
        temp_variable.domain.push_back(yytext[0]);
    }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 204 "main.l"
{
        variables.push_back(temp_variable);
        
        cout << "== Variabila globala: ==" << endl;
        cout << "-> Numele ei: " << temp_variable.name << endl;
        cout << "-> Domeniul ei: { ";
        for (int i = 0; i < temp_variable.domain.size(); i++) {
            if (i != 0) {
                cout << ", ";
            }
            cout << temp_variable.domain[i];
        }
        cout << " }" << endl << endl;

        // De 2 ori pentru ca am si "VARIABLE" si "IN_VARIABLE" pe stack
        yy_pop_state();
        yy_pop_state();
    }
	YY_BREAK


case 15:
YY_RULE_SETUP
#line 225 "main.l"
{
        // Variabile locale -> Aceleasi operatii ca la variabilele globale, doar ca aici nu le afisez direct dupa citire
        temp_variable.name = yytext;
    }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 229 "main.l"
{
        // Formatul de afisare e in AUTOMATON_MAIN sau in GRAMMAR_MAIN
        yy_push_state(L_IN_VARIABLE);
    }
	YY_BREAK


case 17:
YY_RULE_SETUP
#line 236 "main.l"
;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 237 "main.l"
{
        temp_variable.domain.push_back(yytext[0]);
    }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 240 "main.l"
{
        variables.push_back(temp_variable);
        yy_pop_state();
        yy_pop_state();
    }
	YY_BREAK


case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 248 "main.l"
; // ignor " ::= FiniteAutomaton "
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 249 "main.l"
{
        yy_push_state(A_ALPHABET);
    }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 252 "main.l"
{
        yy_push_state(A_STATES);
    }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 255 "main.l"
{
        yy_push_state(A_FINAL_STATES);
    }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 258 "main.l"
{
        yy_push_state(A_INITIAL_STATE);
    }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 261 "main.l"
{
        reset_temp_variable();
        automaton.my_variables++;
        yy_push_state(L_VARIABLE);
    }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 266 "main.l"
{
        // Orice alt string in afara de cazurile de mai sus e inceput de tranzitie
        // ex: q0 -> ...
        if (automaton.transitions.size() == 0) { 
            // daca este prima tranzitie
            cout << "Tranzitiile automatului: " << endl;
        }
        automaton.current_initial = yytext; // salvez starea de inceput a tranzitiei
        yy_push_state(A_TRANSITIONS);
    }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 276 "main.l"
{
        // Dinamic am putut verifica doar sa nu fie mai multe tranzitii cu aceeasi combinatie
        // stare + litera, dar nu am verificat daca nu sunt deloc tranzitii pentru acea pereche
        // verificare determinism automat
        for (string state : automaton.states) {
            for (char letter : automaton.alphabet) {
                if (automaton.transitions.find(state) == automaton.transitions.end() || 
                    automaton.transitions[state].find(letter) == automaton.transitions[state].end() ||
                    automaton.transitions[state][letter] == 0) {
                    automaton.deterministic = false;
                }
            }
        }
        if (automaton.deterministic) {
            cout << "Automatul este de tip DETERMINIST" << endl;
        } else {
            cout << "Automatul este de tip NEDETERMINIST" << endl;
        }
        // Variabilele locale se scriu abia la final de automat
        for (int i = 0; i < automaton.my_variables; i++) {
            cout << "== Variabila locala: ==" << endl;
            cout << "-> Numele ei: " << variables[variables.size() - automaton.my_variables + i].name << endl;
            cout << "-> Domeniul ei: { ";
            for (int j = 0; j < variables[variables.size() - automaton.my_variables + i].domain.size(); j++) {
                if (j != 0) {
                    cout << ", ";
                }
                cout << variables[variables.size() - automaton.my_variables + i].domain[j];
            }
            cout << " }" << endl;
        }
        for (int i = 0; i < automaton.my_variables; i++) {
            variables.pop_back();
        }
        cout << endl;
        yy_pop_state();
    }
	YY_BREAK


case 28:
/* rule 28 can match eol */
YY_RULE_SETUP
#line 316 "main.l"
; // ignor " ::= Grammar "
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 317 "main.l"
{
        yy_push_state(G_NONTERMINALS);
    }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 320 "main.l"
{
        yy_push_state(G_ALPHABET);
    }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 323 "main.l"
{
        yy_push_state(G_START_SYMBOL);
    }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 326 "main.l"
{
        reset_temp_variable();
        grammar.my_variables++;
        yy_push_state(L_VARIABLE);
    }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 331 "main.l"
{
        // Orice alt string in afara de cazurile de mai sus e inceput de regula de productie
        reset_grammar_production_data();
        grammar.nonterminal_count++;
        yy_push_state(G_PRODUCTIONS);
    }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 337 "main.l"
{
        // Ca mai sus, doar ca pentru terminale (cele din alfabet), la regula de productie
        reset_grammar_production_data();
        grammar.terminal_count++;
        yy_push_state(G_PRODUCTIONS);
    }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 343 "main.l"
{
        // Numarul de reguli si tipul gramaticii il pot sti sigur abia la finalul citirii gramaticii
        cout << "Gramatica are " << grammar.production_rules << " reguli de productie" << endl;
        if (grammar.type == GN) {
            cout << "Gramatica este de tip NERESTRICTIONAT" << endl;
        } else if (grammar.type == GDC) {
            cout << "Gramatica este de tip DEPENDENTA DE CONTEXT" << endl;
        } else if (grammar.type == GIC) {
            cout << "Gramatica este de tip INDEPENDENTA DE CONTEXT" << endl;
        } else if (grammar.type == GR) {
            cout << "Gramatica este de tip REGULAT" << endl;
        }
        for (int i = 0; i < grammar.my_variables; i++) {
            cout << "== Variabila locala: ==" << endl;
            cout << "-> Numele ei: " << variables[variables.size() - grammar.my_variables + i].name << endl;
            cout << "-> Domeniul ei: { ";
            for (int j = 0; j < variables[variables.size() - grammar.my_variables + i].domain.size(); j++) {
                if (j != 0) {
                    cout << ", ";
                }
                cout << variables[variables.size() - grammar.my_variables + i].domain[j];
            }
            cout << " }" << endl;
        }
        cout << endl;

        for (int i = 0; i < grammar.my_variables; i++) {
            variables.pop_back();
        }
        yy_pop_state();
    }
	YY_BREAK


case 36:
YY_RULE_SETUP
#line 377 "main.l"
; // ignor virgulele
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 378 "main.l"
{
        // Daca e "variable" trebuie expandat domeniul
        int idx = find_variable(yytext);
        if (idx == -1) {
            // daca string-ul nu a fost gasit drept variabila,
            // adaugam caracterul in alfabet
            automaton.alphabet.push_back(yytext[0]);
        } else {
            // adaugam caracterele din domeniul variabilei
            for (int i = 0; i < variables[idx].domain.size(); i++) {
                automaton.alphabet.push_back(variables[idx].domain[i]);
            }
        }
    }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 392 "main.l"
{
        cout << "Alfabetul automatului: { ";
        for (int i = 0; i < automaton.alphabet.size(); i++) {
            if (i != 0) {
                cout << ", ";
            }
            cout << automaton.alphabet[i];
        }
        cout << " }" << endl;
        yy_pop_state();
    }
	YY_BREAK


case 39:
YY_RULE_SETUP
#line 406 "main.l"
;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 407 "main.l"
{
        automaton.states.push_back(yytext);
    }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 410 "main.l"
{
        // Trebuie scris doar numarul lor, nu si pe ele in sine
        cout << "Numarul de stari: " << automaton.states.size() << endl;
        yy_pop_state();
    }
	YY_BREAK


case 42:
YY_RULE_SETUP
#line 418 "main.l"
;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 419 "main.l"
{
        automaton.final_states.push_back(yytext);
    }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 422 "main.l"
{
        cout << "Starile finale: { ";
        for (int i = 0; i < automaton.final_states.size(); i++) {
            if (i != 0) {
                cout << ", ";
            }
            cout << automaton.final_states[i];
        }
        cout << " }" << endl;
        yy_pop_state();
    }
	YY_BREAK


case 45:
YY_RULE_SETUP
#line 436 "main.l"
{
        cout << "Starea initiala: " << yytext << endl;
    }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 439 "main.l"
{
        yy_pop_state();
    }
	YY_BREAK


case 47:
YY_RULE_SETUP
#line 445 "main.l"
; // ignor sageata si paranteza de la stare de la input
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 446 "main.l"
;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 448 "main.l"
{ // pentru caracterele din alfabet
        int idx = find_variable(yytext);
        if (idx == -1) { // nu e variable
            automaton.transitions[automaton.current_initial][yytext[0]]++;
            // Verific pe loc daca mai exista o tranzitie cu aceeasi combinatie stare + litera
            if (automaton.transitions[automaton.current_initial][yytext[0]] > 1) {
                automaton.deterministic = false;
            }
            // De asemenea, e-tranzitiile fac automatul nedeterminist, deci verific si asta
            if (yytext[0] == 'e') {
                automaton.deterministic = false;
            }
            automaton.last_letters.push_back(yytext[0]);
        } else {
            // este variabila -> trebuie sa adaugam la domeniu
            for (int i = 0; i < variables[idx].domain.size(); i++) {
                automaton.transitions[automaton.current_initial][variables[idx].domain[i]]++;
                if (automaton.transitions[automaton.current_initial][variables[idx].domain[i]] > 1) {
                    automaton.deterministic = false;
                }
                // adaugam caracterele de input ca litere pentru tranzitii
                automaton.last_letters.push_back(variables[idx].domain[i]);
            }
        }
    }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 473 "main.l"
{
        // Daca e variabila poate sa nu fie neaparat in [a-z0-9], ci sa fie string mai lung
        int idx = find_variable(yytext);
        if (idx == -1) {
            cout << "EROARE: Variabila necunoscuta: " << yytext << endl;
        } else {
            // la fel ca mai sus
            for (int i = 0; i < variables[idx].domain.size(); i++) {
                automaton.transitions[automaton.current_initial][variables[idx].domain[i]]++;
                if (automaton.transitions[automaton.current_initial][variables[idx].domain[i]] > 1) {
                    automaton.deterministic = false;
                }
                automaton.last_letters.push_back(variables[idx].domain[i]);
            }
        }
    }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 489 "main.l"
{
        // Acum trebuie sa vad in ce stare se duc literele citite, adica ce e dupa "->"
        yy_push_state(A_TRANSITIONS_END);
    }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 493 "main.l"
{
        yy_pop_state();
    }
	YY_BREAK


case 53:
YY_RULE_SETUP
#line 499 "main.l"
{
        // Scriu tranzitiile pentru toate literele dinaintea sagetii
        for (int i = 0; i < automaton.last_letters.size(); i++) {
            cout << "-> m(" << automaton.current_initial << ", " << automaton.last_letters[i] << ") = " << yytext << endl;
        }
        automaton.last_letters.clear();
    }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 506 "main.l"
{
        yy_pop_state();
    }
	YY_BREAK


case 55:
YY_RULE_SETUP
#line 512 "main.l"
;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 513 "main.l"
;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 514 "main.l"
{
        // Nu se cere nimic cu astia la output, ii ignor complet
        yy_pop_state();
    }
	YY_BREAK


case 58:
YY_RULE_SETUP
#line 521 "main.l"
; // ignor virgule
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 522 "main.l"
{
        // Exact ca la alfabetul automatelor
        int idx = find_variable(yytext);
        if (idx == -1) {
            grammar.alphabet.push_back(yytext[0]);
        } else {
            // adaug toate caracterele din domeniul variabilei
            for (int i = 0; i < variables[idx].domain.size(); i++) {
                grammar.alphabet.push_back(variables[idx].domain[i]);
            }
        }
    }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 534 "main.l"
{
        cout << "Alfabetul gramaticii: { ";
        for (int i = 0; i < grammar.alphabet.size(); i++) {
            if (i != 0) {
                cout << ", ";
            }
            cout << grammar.alphabet[i];
        }
        cout << " }" << endl;
        yy_pop_state();
    }
	YY_BREAK


case 61:
YY_RULE_SETUP
#line 548 "main.l"
;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 549 "main.l"
{
        // Si pe asta il ignor complet
        yy_pop_state();
    }
	YY_BREAK


case 63:
YY_RULE_SETUP
#line 556 "main.l"
; // ignor caracteru de concatenare
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 557 "main.l"
{
        grammar.nonterminal_count++;
    }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 560 "main.l"
{
        grammar.terminal_count++;
    }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 563 "main.l"
{
        // ma ocup de partea din stanga sagetii productiei

        // Am explicat in readme logica conditiilor astea
        grammar.start_size = grammar.nonterminal_count + grammar.terminal_count;
        if (grammar.nonterminal_count == 0) {
            // nu avem neterminale in stanga -> Downgrade la GN
            grammar.type = min(GN, grammar.type);
        } else if (grammar.start_size > 1) {
            // mai mult de un simbol in stanga -> Downgrade la GDC
            grammar.type = min(GDC, grammar.type);
        }

        grammar.nonterminal_count = 0;
        grammar.terminal_count = 0;
        yy_push_state(G_PRODUCTIONS_END);
    }
	YY_BREAK


case 67:
YY_RULE_SETUP
#line 583 "main.l"
; // ignor caracteru de concatenare
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 584 "main.l"
{
        grammar.nonterminal_count++;
        grammar.last_read = yytext; // tin minte ultimul simbol citit
        // pt a verifica daca este "e"
    }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 589 "main.l"
{
        // terminal
        grammar.terminal_count++;
        if (grammar.nonterminal_count >= 1) {
            // avem macar un neterminal in dreapta -> Downgrade la GIC
            grammar.type = min(GIC, grammar.type);
        }
        grammar.last_read = yytext;
    }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 598 "main.l"
{
        int end_size = grammar.nonterminal_count + grammar.terminal_count;
        if (end_size < grammar.start_size && grammar.last_read != "e") {
            // partea dreapta mai mica decat stanga -> Downgrade la GN
            grammar.type = min(GN, grammar.type);
        }

        grammar.nonterminal_count = 0;
        grammar.terminal_count = 0;
        grammar.production_rules++;
    }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 609 "main.l"
{
        // Ca mai sus, dar acum trecem la alta regula cu alt membru stanga, deci pop la starea actuala
        int end_size = grammar.nonterminal_count + grammar.terminal_count;
        if (end_size < grammar.start_size && grammar.last_read != "e") {
            // la fel ca mai sus, Downgrade la GN
            grammar.type = min(GN, grammar.type);
        }

        grammar.nonterminal_count = 0;
        grammar.terminal_count = 0;
        grammar.production_rules++;

        // Am si "G_PRODUCTIONS" si "G_PRODUCTIONS_END" pe stiva
        yy_pop_state();
        yy_pop_state();
    }
	YY_BREAK

case 72:
YY_RULE_SETUP
#line 627 "main.l"
ECHO;
	YY_BREAK
#line 2057 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(IN_COMMENT):
			case YY_STATE_EOF(VARIABLE):
			case YY_STATE_EOF(IN_VARIABLE):
			case YY_STATE_EOF(L_VARIABLE):
			case YY_STATE_EOF(L_IN_VARIABLE):
			case YY_STATE_EOF(AUTOMATON_MAIN):
			case YY_STATE_EOF(A_ALPHABET):
			case YY_STATE_EOF(A_STATES):
			case YY_STATE_EOF(A_FINAL_STATES):
			case YY_STATE_EOF(A_INITIAL_STATE):
			case YY_STATE_EOF(A_TRANSITIONS):
			case YY_STATE_EOF(A_TRANSITIONS_END):
			case YY_STATE_EOF(GRAMMAR_MAIN):
			case YY_STATE_EOF(G_NONTERMINALS):
			case YY_STATE_EOF(G_ALPHABET):
			case YY_STATE_EOF(G_START_SYMBOL):
			case YY_STATE_EOF(G_PRODUCTIONS):
			case YY_STATE_EOF(G_PRODUCTIONS_END):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 359 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    
	YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 359 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 358);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

    static void yy_push_state (int  _new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc( new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc(
					(void *) (yy_start_stack), new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

    static void yy_pop_state  (void)
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    static int yy_top_state  (void)
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_start_stack_ptr) = 0;
    (yy_start_stack_depth) = 0;
    (yy_start_stack) =  NULL;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Destroy the start condition stack. */
        yyfree( (yy_start_stack)  );
        (yy_start_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 627 "main.l"




int main(int argc, char* argv[]) {
    if (argc > 1) {
        if (!(yyin = fopen(argv[1], "r"))) {
            cout << "Fisierul " << argv[1] << " nu a putut fi deschis" << endl;
            return 1;
        }
    } else {
        cout << "Trebuie specificat un fisier de intrare" << endl;
        return 1;
    }
    yylex();
    return 0;
}
